eve_api/urls.py
from django.conf.urls.defaults import *
from django.core.urlresolvers import reverse

from eve_api import views

urlpatterns = patterns('',
    url(r'^eveapi/add/', views.eveapi_add, name="eveapi-add"),
    url(r'^eveapi/update/(?P<userid>\d+)/$', views.eveapi_update, name="eveapi-update"),
    url(r'^eveapi/delete/(?P<userid>\d+)/$', views.eveapi_del, name="eveapi-delete"),
    url(r'^eveapi/refresh/(?P<userid>\d+)/$', views.eveapi_refresh, name="eveapi-refresh"),
    url(r'^eveapi/log/(?P<userid>\d+)/$', views.eveapi_log, name="eveapi-log"),

    url(r'^character/list/$', views.eveapi_character, name="eveapi-characters-list"),
    url(r'^character/(?P<charid>\d+)/$', views.eveapi_character, name="eveapi-character"),

    url(r'^corporation/(?P<corporationid>\d+)/$', views.eveapi_corporation, name="eveapi-corporation"),
    url(r'^corporation/(?P<corporationid>\d+)/export/$', views.eveapi_corporation_members_csv, name="eveapi-corporation-members-csv"),
    url(r'^alliance/(?P<allianceid>\d+)/$', views.eveapi_alliance, name="eveapi-alliance"),
)

eve_api/models/alliance.py
from django.db import models
from django.contrib.auth.models import Group
from eve_api.models import EVEAPIModel

class EVEPlayerAlliance(EVEAPIModel):
    """
    Represents a player-controlled alliance. Updated from the alliance
    EVE XML API puller at intervals.
    """
    name = models.CharField(max_length=255, blank=True, null=False)
    ticker = models.CharField(max_length=15, blank=True, null=False)
    executor = models.ForeignKey('eve_api.EVEPlayerCorporation', blank=True, null=True)
    member_count = models.IntegerField(blank=True, null=True)
    date_founded = models.DateField(blank=True, null=True)
    group = models.ForeignKey(Group, blank=True, null=True)

    class Meta:
        app_label = 'eve_api'
        ordering = ['date_founded']
        verbose_name = 'Alliance'
        verbose_name_plural = 'Alliances'

    def __unicode__(self):
        if self.name:
            return self.name
        else:
            return "(#%d)" % self.id

eve_api/models/character.py
from django.db import models
from django.core.exceptions import ObjectDoesNotExist
from eve_api.app_defines import *
from eve_api.models import EVEAPIModel


class EVEPlayerCharacterSkill(models.Model):
    """
    For our m2m join to EVESkills
    """
    character = models.ForeignKey('eve_api.EVEPlayerCharacter')
    skill = models.ForeignKey('eve_api.EVESkill')
    level = models.IntegerField(default=0)
    skillpoints = models.IntegerField(default=0)
    in_training = models.IntegerField(default=0)

    def __unicode__(self):
        return u"%s - Level %s" % (self.skill, self.level)

    class Meta:
        app_label = 'eve_api'
        verbose_name = 'Player Character Skill'
        verbose_name_plural = 'Player Character Skills'


class EVEPlayerCharacterEmploymentHistory(models.Model):
    """
    Player's corporation history
    """
    record_id = models.IntegerField(primary_key=True, verbose_name="Record ID")
    character = models.ForeignKey('eve_api.EVEPlayerCharacter', related_name='employmenthistory')
    corporation = models.ForeignKey('eve_api.EVEPlayerCorporation', related_name='+')
    start_date = models.DateTimeField(blank=False, null=False, verbose_name="Corporation Join Date")

    @property
    def end_date(self):
        if self.character.employmenthistory.filter(record_id__gt=self.record_id).count():
            return self.character.employmenthistory.filter(record_id__gt=self.record_id).order_by('record_id')[0].start_date
        return None

    def __unicode__(self):
        return u'%s - %s - %s' % (self.record_id, self.character, self.corporation)

    class Meta:
        app_label = 'eve_api'
        verbose_name = 'Player Character Employment History'
        verbose_name_plural = 'Player Character Employment Histories'
        ordering = ['-record_id']

class EVEPlayerCharacter(EVEAPIModel):
    """
    Represents an individual player character within the game. Not to be
    confused with an account.
    """
    name = models.CharField(max_length=255, blank=True, null=False)
    corporation = models.ForeignKey('eve_api.EVEPlayerCorporation', blank=True, null=True)
    corporation_date = models.DateTimeField(blank=True, null=True, verbose_name="Corporation Join Date")
    race = models.IntegerField(blank=True, null=True, choices=API_RACES_CHOICES)
    gender = models.IntegerField(blank=True, null=True, choices=API_GENDER_CHOICES)
    balance = models.FloatField("Account Balance", blank=True, null=True)
    attrib_intelligence = models.IntegerField("Intelligence", blank=True, null=True)
    attrib_memory = models.IntegerField("Memory", blank=True, null=True)
    attrib_charisma = models.IntegerField("Charisma", blank=True, null=True)
    attrib_perception = models.IntegerField("Perception", blank=True, null=True)
    attrib_willpower = models.IntegerField("Willpower", blank=True, null=True)
    total_sp = models.IntegerField("Total SP", blank=True, null=True)
    security_status = models.FloatField("Security Status", blank=True, null=True)
    current_location_id = models.IntegerField("Current Location ID", blank=True, null=True)
    last_login = models.DateTimeField(blank=True, null=True,
                                            verbose_name="Last Login Date/Time",
                                            help_text="The last time this character logged into EVE")
    last_logoff = models.DateTimeField(blank=True, null=True, verbose_name="Last Logoff Date/Time",
                                            help_text="The last time this character logged off EVE")
    roles = models.ManyToManyField('eve_api.EVEPlayerCharacterRole', blank=True, null=True,
                                            help_text="Roles associated with this character")
    skills = models.ManyToManyField('eve_api.EVESkill', through='eve_api.EVEPlayerCharacterSkill')

    @property
    def director(self):
        """ Returns a bool to indicate if the character is a director """
        try:
            self.roles.get(name="roleDirector")
            return True
        except ObjectDoesNotExist:
            return False

    @property
    def current_training(self):
        """ Returns the current skill in training """
        try:
            return self.eveplayercharacterskill_set.get(in_training__gt=0)
        except EVEPlayerCharacterSkill.DoesNotExist:
            return None

    @property
    def account(self):
        if self.eveaccount_set.filter(api_status=API_STATUS_OK).count():
            return self.eveaccount_set.filter(api_status=API_STATUS_OK)[0]
        return None

    @property
    def active_key(self):
        if self.eveaccount_set.count():
            return self.eveaccount_set.filter(api_status=API_STATUS_OK).count() > 0
        return False

    @models.permalink
    def get_absolute_url(self):
        return ('eveapi-character', [self.pk])

    def __unicode__(self):
        if self.name:
            return self.name
        else:
            return u"(%d)" % self.id

    class Meta:
        app_label = 'eve_api'
        verbose_name = 'Character'
        verbose_name_plural = 'Characters'

        permissions = (
            ("can_view_all_characters", "Can view any character profile"),
        )

eve_api/models/corporation.py
from django.db import models
from django.contrib.auth.models import Group
from gargoyle import gargoyle
from eve_api.models import EVEAPIModel
from eve_api.app_defines import *

class EVEPlayerCorporation(EVEAPIModel):
    """
    Represents a player-controlled corporation. Updated from a mixture of
    the alliance and corporation API pullers.
    """
    name = models.CharField(max_length=255, blank=True, null=True)
    ticker = models.CharField(max_length=15, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    url = models.URLField(verify_exists=False, blank=True, null=True)
    ceo_character = models.ForeignKey('eve_api.EVEPlayerCharacter', blank=True, null=True)
    alliance = models.ForeignKey('eve_api.EVEPlayerAlliance', blank=True, null=True)
    alliance_join_date = models.DateField(blank=True, null=True)
    tax_rate = models.FloatField(blank=True, null=True)
    member_count = models.IntegerField(blank=True, null=True)
    shares = models.IntegerField(blank=True, null=True)

    # Logo generation stuff
    logo_graphic_id = models.IntegerField(blank=True, null=True)
    logo_shape1 = models.IntegerField(blank=True, null=True)
    logo_shape2 = models.IntegerField(blank=True, null=True)
    logo_shape3 = models.IntegerField(blank=True, null=True)
    logo_color1 = models.IntegerField(blank=True, null=True)
    logo_color2 = models.IntegerField(blank=True, null=True)
    logo_color3 = models.IntegerField(blank=True, null=True)

    group = models.ForeignKey(Group, blank=True, null=True)

    @property
    def directors(self):
        """ Return a queryset of corporate Directors """
        return self.eveplayercharacter_set.filter(roles__name="roleDirector")

    @property
    def api_keys(self):
        """ Returns the number of characters with stored API keys """
        return self.eveplayercharacter_set.filter(eveaccount__isnull=False).distinct().count()

    @property
    def active_api_keys(self):
        """ Returns the number of characters with stored and active API keys """
        return self.eveplayercharacter_set.filter(eveaccount__isnull=False, eveaccount__api_status=API_STATUS_OK).distinct().count()

    @property
    def director_api_keys(self):
        if gargoyle.is_active('eve-cak'):
            return self.directors.filter(eveaccount__isnull=False, eveaccount__api_keytype__in=[API_KEYTYPE_CORPORATION, API_KEYTYPE_FULL], eveaccount__api_status=API_STATUS_OK)
        else:
            return self.directors.filter(eveaccount__isnull=False, eveaccount__api_keytype=API_KEYTYPE_FULL, eveaccount__api_status=API_STATUS_OK)

    @property
    def api_key_coverage(self):
        """ Returns the percentage coverage of API keys for the corporation's members """

        # Check if we have a full director key, see if we can base our assumptions off what is in auth already
        if self.director_api_keys.count():
            membercount = self.eveplayercharacter_set.count()
        else:
            membercount = self.member_count

        if self.api_keys and membercount:
            return (float(self.api_keys) / membercount) * 100
        else:
            return float(0.0)

    @property
    def average_sp(self):
        return self.eveplayercharacter_set.aggregate(models.Avg('total_sp'))['total_sp__avg']

    @models.permalink
    def get_absolute_url(self):
        return ('eveapi-corporation', [self.pk])

    class Meta:
        app_label = 'eve_api'
        verbose_name = 'Corporation'
        verbose_name_plural = 'Corporations'

    def __unicode__(self):
        if self.name:
            return self.name
        else:
            return u"Corp #%d" % self.id

eve_api/templates/eve_api/add.html
{% extends "base.html" %}

{% load gargoyle_tags %}

{% block title %}Add EVE API Key{% endblock %}

{% block content %}

{% ifswitch eve-cak %}
<p>Please fill in your API key details and a optional description. You can create a API key on the <a href="https://support.eveonline.com/api/Key/CreatePredefined/59638024/0/false">API support site</a></p>
{% else %}
<p>Please fill in your API key as provided on the <a href="http://eve-online.com/api">EVE Online API page</a> and a optional description.</p>
{% endifswitch %}

<form action="{% url eve_api.views.eveapi_add %}" method="post">
<table>
{{ form.as_table }}
</table>
<br />
{% csrf_token %}
<input type="submit" value="Add Key" />
</form>

{% endblock %}

eve_api/templates/eve_api/alliance.html
{% extends "base.html" %}

{% load humanize %}
{% load naturaltimediff %}

{% block content %}
<div class="alliance_info">
	<h1>{{ alliance.name }}</h1>

        <ul>
            <li><b>Member Count:</b> {{ alliance.member_count }}</li>
            <li><b>Executor Corporation:</b> <a href="{% url eveapi-corporation alliance.executor.id %}">{{ alliance.executor }}</a></li>
            <li><b>Alliance Leader:</b> {{ executor }}</li>
        </ul>

        <h2>Corporations</h2>

        <table>
        <tr><th>Name</td><th>Members</th><th>Average SP</th><th>API Coverage</th><th>Director Key?</th></tr>
        {% for corp in corporations %}
        <tr><td><a href="{% url eveapi-corporation corp.id %}">{{ corp }}</a></td><td>{{ corp.member_count }}</td><td>{{ corp.average_sp|intcomma }}</td><td>{{ corp.api_key_coverage|floatformat:2 }}%</td><td>{{ corp.director_api_keys.count }}</td></tr>
        {% endfor %}
        </table>
</div>
{% endblock %}

eve_api/templates/eve_api/character.html
{% extends "base.html" %}

{% load humanize %}
{% load naturaltimediff %}
{% block content %}

<div class="character_info">
	<h1>{{ character.name }}</h1>

	<div class="character_portrait">
		<img src="https://image.eveonline.com/Character/{{ character.id }}_256.jpg" />
	</div>
	
	<div class="character_corporation">
		<span><a href="{% url eveapi-corporation character.corporation.id %}">{{ character.corporation.ticker }}</a></span>
		<img src="https://image.eveonline.com/Corporation/{{ character.corporation.id }}_64.png" />
	</div>
	
        {% if character.corporation.alliance %}
	<div class="character_alliance">
		<span><a href="{% url eveapi-alliance character.corporation.alliance.id %}">{{ character.corporation.alliance.ticker }}</a></span>
		<img src="https://image.eveonline.com/Alliance/{{ character.corporation.alliance.id }}_64.png" />
	</div>
        {% endif %}

	<div class="character_attributes">
		<h2>Attributes</h2>
		
		<ul>
			<li><span class="stat">Race:</span> <span class="value">{{ character.get_race_display }}</span></li>
			<li><span class="stat">Gender:</span> <span class="value">{{ character.get_gender_display }}</span></li>
			<li><span class="stat">Corporation:</span> <a href="{% url eveapi-corporation character.corporation.id %}">{{ character.corporation.name }}</a></span></li>
			<li><span class="stat">Joined Corporation:</span> <span class="value">{{ character.corporation_date|date:"Y/m/d H:i:s" }} ({{ character.corporation_date|naturaltimediff }})</span></li>
                        {% if character.corporation.alliance %}
			<li><span class="stat">Alliance:</span> <span class="value"><a href="{% url eveapi-alliance character.corporation.alliance.id %}">{{ character.corporation.alliance.name }}</a></span></li>
                        {% endif %}
			<li><span class="stat">Security Status:</span> {{ character.security_status|floatformat:2 }}</span></li>
			<li><span class="stat">Director:</span> <span class="value">{{ character.director }}</span></li>
                        {% if character.current_training %}
                        <li><spam class="stat">Training:</span> <span class="Value">{{ character.current_training.skill.name}} to Level {{ character.current_training.in_training }}</li>
                        {% endif %}
		</ul>
	</div>

	<div class="character_stats">
		<h2>Stats</h2>
		
		<table>
			<tr><th>Stat</th><th>Value</th></tr>
			<tr><td class="stat">Intelligence</td><td> {{ character.attrib_intelligence }}</td></tr>
			<tr><td class="stat">Memory</td><td>{{ character.attrib_memory }}</td></tr>
			<tr><td class="stat">Charisma</td><td>{{ character.attrib_charisma }}</td></tr>
			<tr><td class="stat">Perception</td><td>{{ character.attrib_perception }}</td></tr>
			<tr><td class="stat">Willpower</td><td>{{ character.attrib_willpower }}</td></tr>
		</table>
	</div>

	<div class="character_skills">
		<h2>Skills</h2>
		
		<div class="skill_controls">
			<a href=#" id="openAll">Open All</a>
			<a href=#" id="collapseAll">Collapse All</a>
		</div>

		<table>

            {% for group in skillTree %}
            {{group.items}}
			<tr class="skill_heading" id="{{ group.1 }}"><th colspan=2>{{ group.1 }}</th><th>{{ group.0|intcomma }}</th></tr>
			{% for skill in group.2 %}
                        {% if skill.in_training %}
                        <tr class="child intraining" parent="{{ group.1 }}"><td>{{ skill.skill.name }} - Training to Level {{ skill.in_training }}</td><td><img src="{{ STATIC_URL }}img/skills/level{{ skill.level }}t.gif" alt="Level {{ skill.level }}" /></td><td>{{ skill.skillpoints|intcomma }} SP</td></tr>
                        {% else %}
						<tr class="child" parent="{{ group.1 }}"><td>{{ skill.skill.name }} </td><td><img src="{{ STATIC_URL }}img/skills/level{{ skill.level }}.gif" alt="Level {{ skill.level }}" /></td><td>{{ skill.skillpoints|intcomma }} SP</td></tr>
                        {% endif %}
			{% endfor %}
			{% endfor %}
			<tr><th colspan=2>Total SP</th><th>{{ character.total_sp|intcomma }} SP</th></tr>
		</table>
	</div>

        {% if employmenthistory.count %}
        <div class="character_employmenthistory">
                <h2>Employment History</h2>

                <table>
                <tr><th>Corporation</th><th>Join Date</th><th>Leave Date</th></tr>
                {% for hist in employmenthistory %}
                <tr><td><a href="{% url eveapi-corporation hist.corporation.id %}">{{ hist.corporation.name }}</a></td><td>{{ hist.start_date }}</td><td>{% if hist.end_date %}{{ hist.end_date }}{% endif %}</td></tr>
                {% endfor %}
                </table>
        </div>
        {% endif %}

</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript">
	$(function(){
		$(".skill_heading")
                    .css("cursor", "pointer")
                    .attr("title", "Click to expand/collapse")
                    .click(function(){
                        $('tr[parent$=' + $(this).attr('id') + ']').toggle();
    		    });
		
		$("#openAll").bind("click", function(e){
			e.preventDefault();
                        $(".child").show();
		});
		
		$("#collapseAll").bind("click", function(e){
			e.preventDefault();
			$(".child").hide();
		});

                $('tr[parent]').hide();
	});
</script>

{% endblock %}

eve_api/templates/eve_api/character_list.html
{% extends "base.html" %}
{% load humanize %}
{% block content %}

<h1>Character List</h1>

<table>
<tr><th>Character Name</th><th>Corporation</th><th>Alliance</th><th>Skillpoints</th><th>Training</th></tr>
{% for acc in accounts %}
{% if acc.characters.count %}
<tr><th colspan=5>Key {{ acc.pk }} {% if acc.training == 0 %}<font color="#F87217">(No Character Training)</font>{% endif %}</th></tr>
{% for char in acc.characters.all %}
<tr><td><a href="{% url eveapi-character char.id %}">{{ char.name }}</a></td>
    <td><a href="{% url eveapi-corporation char.corporation.id %}">{{ char.corporation }}</a></td>
    <td>{% if char.corporation.alliance %}<a href="{% url eveapi-alliance char.corporation.alliance.id %}">{{ char.corporation.alliance }}</a>{% endif %}</td>
    <td style="text-align: right;">{{ char.total_sp|intcomma }} SP</td>
    <td>{% if char.current_training %}{{ char.current_training.skill.name }} to Level {{ char.current_training.in_training }}{% endif %}</td> 
</tr>
{% endfor %}
{% endif %}
{% endfor %}
</table>

{% endblock %}

eve_api/templates/eve_api/corporation.html
{% extends "base.html" %}

{% load humanize %}
{% load naturaltimediff %}
{% load pagination_tags %}

{% block content %}

<div class="corporation_info">
	<h1>{{ corporation.name }}</h1>

        <ul>
        <li><b>Member Count:</b> {{ corporation.member_count }}</li>
        <li><b>Known Members:</b> {{ corporation.eveplayercharacter_set.count }}</li>
        {% if view_members %}
        <li><b>Full Director API Available: {% if corporation.director_api_keys %}<span style="color: green;">Yes</span>{% else %}<span style="color: red;">No</span>{% endif %}</b></li>
        <li><b>Members with API Keys:</b> {{ corporation.api_keys }}</li>
        <li><b>Members with Active API Keys:</b> {{ corporation.active_api_keys }}</li>
        <li><b>API Coverage:</b> {{ corporation.api_key_coverage|floatformat:2 }}%</li>
        {% endif %}
        </ul>

        {% if view_members %}
        <table>
        <tr><th>Name</th><th>Skillpoints</th><th>Join Date</th><th>Director?</th><th>Roles?</th><th>API Key?</th><th>Key Active?</th></tr>
        {% autopaginate members 20 %}
        {% for char in members %}
        <tr><td><a href="{% url eveapi-character char.id %}">{{ char.name }}</a></td><td>{% if char.total_sp %}{{ char.total_sp|intcomma }} SP{% endif %}</td><td>{{ char.corporation_date }}</td><td>{% if char.director %}Yes{% endif %}</td><td>{% if char.eveaccount_set.count %}{% if char.roles.count %}Yes{% else %}No{% endif %}{% endif %}<td>{% if char.eveaccount_set.count %}Yes{% else %}<span style="color: red;">No</span>{% endif %}</td><td>{% if char.active_key %}Yes{% else %}<span style="color: red;">No</span>{% endif %}</td></tr>
        {% endfor %}
        </table>
        {% paginate %}

        <p><a href="{% url eveapi-corporation-members-csv corporation.id %}">Export as CSV</a></p>
        {% endif %}

</div>

{% endblock %}

eve_api/templates/eve_api/log.html
{% extends "base.html" %}

{% block title %}EVE API Access Logs{% endblock %}

{% block content %}
<h1>Access Logs for API Key {{ userid }}</h1>
<table>
<tr><th>Service ID</th><th>Date / Time</th><th>API</th></tr>
{% for log in logs %}
<tr><td>{{ log.service }}</td>
    <td>{{ log.time_access }}</td>
    <td>{{ log.document }}</td>
</tr>
{% endfor %}
</table>
{% endblock %}

eve_api/templates/eve_api/update.html
{% extends "base.html" %}

{% block title %}Update EVE API Key{% endblock %}

{% block content %}
<p>Please update your API key as provided on the <a
href="http://eve-online.com/api">EVE Online API
page</a> and a optional description.</p>

<form action="{% url eveapi-update acc.api_user_id %}" method="post">
<table>
{{ form.as_table }}
</table>
<br />
{% csrf_token %}
<input type="submit" value="Add Key" />
</form>

{% endblock %}